# Generated by Django 2.0.1 on 2018-02-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceMonitoring', '0002_auto_20180201_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='simulated_time',
            field=models.CharField(max_length=20),
        ),
    ]
