# Generated by Django 2.0.1 on 2018-02-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceMonitoring', '0003_auto_20180202_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
