# Generated by Django 2.0.1 on 2018-02-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceMonitoring', '0004_auto_20180202_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
